image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 5006
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: pipenv install # runs during prebuild
    command: pipenv install && pipenv install --dev
vscode:
  extensions:
    - ms-python.python@2019.11.50794:o+QLHnb+xFH1zuBM7u1VIw==
